### ISSUE TITLE
MLIR / LLVM version 16

### ISSUE THREAD

**Issue by nick-lehmann** [femtomc/mlir-sys#18]
A little bit more than month ago, the stable version of LLVM 16 was released. Unfortunately, the build script of this projects has a hardcoded expectation to find a major version of 15 when invoking `llvm-config --version`. Hence, the build fails if you install version 16.

I bumped the expected version to 16 locally, and the build worked flawless as far as I can tell. Do you have any intention on bumping the version upstream as well? Or accept a PR that does so? If yes, would the next version of `mlir-sys` simply have a hardcoded version of 16 or accept both 15 and 16?

P.S. Thanks for the great work 👍🏻 I use this project in my master thesis and it helped me quite a lot to get up and running ❤️

**Comment by femtomc** [comment]
@nick-lehmann -- the latest `crate` should now be up to date with 16
