### ISSUE TITLE
LLVM 18 Support

### ISSUE THREAD

**Issue by edg-l** [femtomc/mlir-sys#34]
It would be nice if you can provide support for LLVM 18 too, see https://github.com/raviqqe/melior/issues/405

Maybe release it as a .rc like llvm itself so its opt in in semver.

**Comment by raviqqe** [comment]
Just so you know, we can't deploy the changes until it lands on Homebrew as we use it for testing.

**Comment by edg-l** [comment]
https://github.com/Homebrew/homebrew-core/pull/165206

**Comment by edg-l** [comment]
brew takes so long... i see the CI uses ubuntu, what about switching to https://apt.llvm.org/ which is more official-y and updated way more frequently?

**Comment by raviqqe** [comment]
We can do that too. But Melior still need it for tests on macOS...

**Comment by edg-l** [comment]
i did that on my open pr
