### ISSUE TITLE
Version bump for LLVM/MLIR 18 support

### ISSUE THREAD

**Issue by raviqqe** [femtomc/mlir-sys#40]
@femtomc Can you bump a version of the crate for this?

**Comment by femtomc** [comment]
Of course, I’ll handle this today.

**Comment by raviqqe** [comment]
Thanks!

**Comment by femtomc** [comment]
Should I bump versions in README?

**Comment by raviqqe** [comment]
Yes, please! Thanks for the catch!

**Comment by edg-l** [comment]
Can we get this in?

**Comment by femtomc** [comment]
All set! Thanks for patience

**Comment by femtomc** [comment]
@raviqqe @edg-l Please send me your `crates.io` user names so I can add you to owners, so you can self publish if I'm waylaid.

**Comment by raviqqe** [comment]
Thanks! Mine is just [`raviqqe`](https://crates.io/users/raviqqe).

**Comment by edg-l** [comment]
Mine is edg-l
