### ISSUE TITLE
v0.2 on crates.io

### ISSUE THREAD

**Issue by raviqqe** [femtomc/mlir-sys#9]
Can you make a new release on [crates.io](https://crates.io/crates/mlir-sys) for v0.2?

**Comment by femtomc** [comment]
@raviqqe I tried to do this this morning, but ran into an issue.

```
error: failed to build archive: Opaque pointers are only supported in -opaque-pointers mode (Producer: 'LLVM15.0.0' Reader: 'LLVM 14.0.6-rust-1.64.0-nightly')

error: could not compile `mlir-sys` due to previous error
error: failed to verify package tarball
```

Is this due to mismatch between Rust LLVM version and the build source version?

**Comment by femtomc** [comment]
@raviqqe I solved this by just `rustup update` -- so I perhaps do not need to know the exact source of the error.

A new version (`0.1.3`) should be available on `crates.io` now.

**Comment by raviqqe** [comment]
Thanks you so much!
